on: 
  workflow_dispatch

jobs:
  buildit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: mvn clean install -DskipTests=true
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: apps